INSERT INTO depts (dept_name)
VALUES  
    ('Head Coach'),
    ('Coaching'),
    ('Offense'),
    ('Defense'),
    ('Special Teams');

INSERT INTO roles (title, salary)
VALUES
    ('HC', 4000000),
    ('DC (acting)', 2000000),
    ('OC', 2000000),
    ('STC', 2000000),
    ('C', 5000000),
    ('FB', 5000000),
    ('LG', 5000000),
    ('LT', 5000000),
    ('QB', 5000000),
    ('RB', 5000000),
    ('RG', 5000000),
    ('RT', 5000000),
    ('TE', 5000000),
    ('WR', 5000000),
    ('FS', 3000000),
    ('LCB', 3000000),
    ('LDE', 3000000),
    ('LDT', 3000000),
    ('MLB', 3000000),
    ('RCB', 3000000),
    ('RDE', 3000000),
    ('RDT', 3000000),
    ('SLB', 3000000),
    ('SS', 3000000),
    ('WLB', 3000000),
    ('H', 1000000),
    ('KR', 1000000),
    ('LS', 1000000),
    ('P', 1000000),
    ('PK', 1000000),
    ('PR', 1000000);

INSERT INTO employees (first_name, last_name, manager_id)
VALUES
  ('Bill', 'Belichick', 1),
('Steve', 'Belichick ', 2),
('Josh', 'McDaniels', 3),
('Cameron', 'Achord', 4),
('David', 'Andrews', NULL),
('Ted', 'Karras', NULL),
('Jakob', 'Johnson', NULL),
('Devin', 'McCourty', NULL),
('Cody', 'Davis', NULL),
('Joshuah', 'Bledsoe', NULL),
('Jake', 'Bailey', NULL),
('Gunner', 'Olszewski', NULL),
('J.J.', 'Taylor', NULL),
('Kyle', 'Dugger', NULL),
('J.C.', 'Jackson', NULL),
('Myles', 'Bryant', NULL),
('Jonathan', 'Jones', NULL),
('Deatrich', 'Wise Jr.', NULL),
('Lawrence', 'Guy', NULL),
('Christian', 'Barmore', NULL),
('Ted', 'Karras', NULL),
('Mike', 'Onwenu', NULL),
('Joe', 'Cardona', NULL),
('Isaiah', 'Wynn', NULL),
('Yodny', 'Cajuste', NULL),
('Justin', 'Herron', NULL),
('DontA', 'Hightower', NULL),
('JaWhaun', 'Bentley', NULL),
('Jahlani', 'Tavai', NULL),
('Jake', 'Bailey', NULL),
('Nick', 'Folk', NULL),
('Mac', 'Jones', NULL),
('Brian', 'Hoyer', NULL),
('Jarrett', 'Stidham', NULL),
('Damien', 'Harris', NULL),
('Rhamondre', 'Stevenson', NULL),
('Brandon', 'Bolden', NULL),
('Jalen', 'Mills', NULL),
('Joejuan', 'Williams', NULL),
('Shaun', 'Wade', NULL),
('Chase', 'Winovich', NULL),
('Henry', 'Anderson', NULL),
('Davon', 'Godchaux', NULL),
('Carl', 'Davis', NULL),
('Byron', 'Cowart', NULL),
('Shaq', 'Mason', NULL),
('Ted', 'Karras', NULL),
('Yasir', 'Durant', NULL),
('Jamie', 'Collins Sr.', NULL),
('Calvin', 'Munson', NULL),
('Kyle', 'Dugger', NULL),
('Adrian', 'Phillips', NULL),
('Justin', 'Bethel', NULL),
('Hunter', 'Henry', NULL),
('Jonnu', 'Smith', NULL),
('Devin', 'Asiasi', NULL),
('Matthew', 'Judon', NULL),
('Ronnie', 'Perkins', NULL),
('Brandon', 'King', NULL),
('Jakobi', 'Meyers', NULL),
('Nelson', 'Agholor', NULL),
('Kendrick', 'Bourne', NULL),
('NKeal', 'Harry', NULL),
('Matthew', 'Slater', NULL);